### ISSUE TITLE
Append is unsafe!

### ISSUE THREAD

**Issue by lehins** [haskell-repa/repa#11]
Appending two arrays with non-matching outer dimensions will result in unsafe indexing beyond the array:

```haskell
λ> let toIx (Z :. i :. j) = (i, j)
λ> let toIx2 (Z :. i :. j) = (10 + i, 20 + j)
λ> let a1 = fromFunction ((Z :. 3 :. 2) :: DIM2) toIx
λ> let a2 = R.fromFunction ((Z :. 2 :. 2) :: DIM2) toIx2
λ> R.toList $ R.computeUnboxedS $ R.append a1 (R.computeUnboxedS a2)
[(0,0),(0,1),(10,20),(10,21),(1,0),(1,1),(11,20),(11,21),(2,0),(2,1),(140453511980952,140453511979256),(32,283763108473)]
```

P.S. There is no way to create a ticket on [trac](http://repa.ouroborus.net/) without an account there, so this issue is submitted here.

**Comment by tmcdonell** [comment]
What was the extent of the result? (if you remove the `toList`)

**Comment by lehins** [comment]
```haskell
λ> R.extent (R.append a1 (R.computeUnboxedS a2))
(Z :. 3) :. 4
```

**Comment by tmcdonell** [comment]
I believe it needs to take the intersection of the lower dimensional component [here](https://github.com/haskell-repa/repa/blob/master/repa/Data/Array/Repa/Operators/IndexSpace.hs#L57).

**Comment by lehins** [comment]
Yes, one of the two would work:
```haskell
fnExtent (sh1 :. i) (sh2  :. j)
    = intersectDim sh1 sh2 :. (i + j)
```
or
```haskell
fnExtent (sh1 :. i) (sh2  :. j)
    | sh1 /= sh2 = error "Lower dimension mismatch"
    | otherwise = sh1 :. (i + j)
```
I'd rather go with the latter one, since you normally don't expect to loose elements during an `append` operation (unlike say with a `zipWith`), but that's just me. Either way is better than reading memory that is not an array.

**Comment by tmcdonell** [comment]
FWIW Accelerate takes the first approach, which I think was just a preference to not throw errors (can't remember), but I agree maybe that is more surprising behaviour. I'd be happy with either approach.
